MAX_QUESTIONS = 5
MAX_HINT_COUNT = 3
RELEVANCE_HINT_THRESHOLD = 70
MAX_RESUME_LENGTH = 12000
MAX_JD_LENGTH = 6000
MAX_SEARCH_RESULTS = 3
MAX_PROJECT_READMES = 10

RETRY_MAX_ATTEMPTS = 3
RETRY_WAIT_MULTIPLIER = 1
RETRY_MIN_WAIT = 1
RETRY_MAX_WAIT = 6

LLM_DEFAULT_TEMPERATURE = 0.1
LLM_FAST_MODEL = "llama-3.3-70b-versatile"
LLM_SMART_MODEL = "llama-3.3-70b-versatile"

LLM_TEMP_EXTRACTION = 0.1
LLM_TEMP_ALIGNMENT = 0.1
LLM_TEMP_VALIDATION = 0.1
LLM_TEMP_QUERY = 0.2
LLM_TEMP_SUMMARY = 0.3
LLM_TEMP_PROJECT = 0.3
LLM_TEMP_STRATEGY = 0.2
LLM_TEMP_QUESTION = 0.3
LLM_TEMP_ANALYSIS = 0.1
LLM_TEMP_HINT = 0.4
LLM_TEMP_EVALUATION = 0.1
LLM_TEMP_REPORT = 0.1

HTTP_TIMEOUT = 15.0

CV_EXTRACT_FIELDS = ["personal_info", "education", "experience", "extracted_skills", "project_links"]
ALIGNMENT_FIELDS = ["job_requirements", "matched_skills", "missing_skills"]