"""add resume_id to document_embedding to filtering

Revision ID: c316c71079c3
Revises: a2d91fc2f981
Create Date: 2026-04-29 08:34:57.786870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c316c71079c3'
down_revision: Union[str, Sequence[str], None] = 'a2d91fc2f981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_embeddings', sa.Column('resume_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_document_embeddings_resume_id'), 'document_embeddings', ['resume_id'], unique=False)
    op.create_foreign_key(None, 'document_embeddings', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_embeddings', type_='foreignkey')
    op.drop_index(op.f('ix_document_embeddings_resume_id'), table_name='document_embeddings')
    op.drop_column('document_embeddings', 'resume_id')
    # ### end Alembic commands ###
