import enum


class InterviewStatus(str, enum.Enum):
	PENDING = "PENDING"
	ANALYZING_RESUME = "ANALYZING_RESUME"
	ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
	FAILED_ANALYSIS = "FAILED_ANALYSIS"
	INTERVIEW_IN_PROGRESS = "INTERVIEW_IN_PROGRESS"
	COMPLETED = "COMPLETED"
